# Generated by Django 4.2 on 2023-05-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='cover_image',
            field=models.ImageField(default='logo1.jpg', upload_to='profile_pictures'),
        ),
    ]
